services:
  fede-work:
    image: fede-work:latest
    networks:
      - traefik_traefik_network
    deploy:
      labels:
        - traefik.http.routers.fede-work.rule=Host(`fede.work`)
        - traefik.http.services.fede-work-service.loadbalancer.server.port=8080

networks:
  traefik_traefik_network:
    external: true
